### ISSUE TITLE
Can't clear datepickerrange

### ISSUE THREAD

**Issue by mauroalejandrojm** [snehilvj/dash-mantine-components#212]
If I use the percistence_type="session" or "local" I'm getting this error:
This error happen after setting a value for the datepickerrange, then clearing the values, then clicking the datepicker again, which generates a None value for the datepicker, 

Note: Now that I noticed the datepicker range is inside a menu component. 
Below is the traceback of the error.

Cannot read properties of null (reading '0'):

(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
TypeError: Cannot read properties of null (reading '0')

    at http://127.0.0.1:8051/_dash-component-suites/dash_mantine_components/dash_mantine_components.v0_12_1m1698945414.js:2:519254

    at renderWithHooks (http://127.0.0.1:8051/_dash-component-suites/dash/deps/react-dom@16.v2_14_0m1698945228.14.0.js:14938:20)

    at updateForwardRef (http://127.0.0.1:8051/_dash-component-suites/dash/deps/react-dom@16.v2_14_0m1698945228.14.0.js:16951:22)

    at beginWork (http://127.0.0.1:8051/_dash-component-suites/dash/deps/react-dom@16.v2_14_0m1698945228.14.0.js:18780:18)

    at HTMLUnknownElement.callCallback (http://127.0.0.1:8051/_dash-component-suites/dash/deps/react-dom@16.v2_14_0m1698945228.14.0.js:182:16)

    at Object.invokeGuardedCallbackDev (http://127.0.0.1:8051/_dash-component-suites/dash/deps/react-dom@16.v2_14_0m1698945228.14.0.js:231:18)

    at invokeGuardedCallback (http://127.0.0.1:8051/_dash-component-suites/dash/deps/react-dom@16.v2_14_0m1698945228.14.0.js:286:33)

    at beginWork$1 (http://127.0.0.1:8051/_dash-component-suites/dash/deps/react-dom@16.v2_14_0m1698945228.14.0.js:23338:9)

    at performUnitOfWork (http://127.0.0.1:8051/_dash-component-suites/dash/deps/react-dom@16.v2_14_0m1698945228.14.0.js:22292:14)

    at workLoopSync (http://127.0.0.1:8051/_dash-component-suites/dash/deps/react-dom@16.v2_14_0m1698945228.14.0.js:22265:24).

**Comment by mauroalejandrojm** [comment]
Also more than three datepickers inside a menu element and connected to a callback its collapsing the server, probably a memory leak or something like that, If you play too much with the datepickers in the documentation page this also seems to happen.

**Comment by mauroalejandrojm** [comment]
I tested v0.13.0a3 and the issue has been fixed using mantine v6, so I'm going to close the issue, if any other person experiences the same, please use the alpha release for now.
