### ISSUE TITLE
 r.useId is not a function

### ISSUE THREAD

**Issue by stpnvkirill** [snehilvj/dash-mantine-components#240]
I encountered an error in version 0.14.0

Application Code:

```
from dash import Dash
import dash_mantine_components as dmc


app = Dash(__name__)


app.layout = dmc.MantineProvider(
    [
        dmc.AppShell(
            [
                dmc.AppShellHeader('children'),
                dmc.AppShellNavbar('children'),
                dmc.AppShellMain('children')
            ],
            header={'height': 60},
            navbar={
                'width': 300,
                "breakpoint": 'sm',
                "collapsed": {"mobile": True},
            },
            padding="md"
        )
    ]
)

if __name__ == '__main__':
    app.run(debug=True)
```
 

error:

 
```
(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
TypeError: r.useId is not a function

    at t.useRandomClassName (http://127.0.0.1:8050/_dash-component-suites/dash_mantine_components/dash_mantine_components.v0_14_0m1713158318.js:2:1539028)

    at http://127.0.0.1:8050/_dash-component-suites/dash_mantine_components/dash_mantine_components.v0_14_0m1713158318.js:2:1530952

    at renderWithHooks (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_16_1m1713158328.14.0.js:14938:20)

    at updateForwardRef (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_16_1m1713158328.14.0.js:16951:22)

    at beginWork (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_16_1m1713158328.14.0.js:18780:18)

    at HTMLUnknownElement.callCallback (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_16_1m1713158328.14.0.js:182:16)

    at Object.invokeGuardedCallbackDev (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_16_1m1713158328.14.0.js:231:18)

    at invokeGuardedCallback (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_16_1m1713158328.14.0.js:286:33)

    at beginWork$1 (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_16_1m1713158328.14.0.js:23338:9)

    at performUnitOfWork (http://127.0.0.1:8050/_dash-component-suites/dash/deps/react-dom@16.v2_16_1m1713158328.14.0.js:22292:14)
```

layout is not loading

**Comment by bufsim** [comment]
try to add 
import dash 
end 
dash._dash_renderer._set_react_version('18.2.0')
before
app = Dash(__name__)

**Comment by milosv-vtool** [comment]
Add `.env` file in your root folder and add this enivroment variable `REACT_VERSION="18.2.0"`
