### ISSUE TITLE
`MantineProvider` was not found in component tree after bundling with pyapp

### ISSUE THREAD

**Issue by matt-sd-watson** [snehilvj/dash-mantine-components#293]
I have a Flask/dash application that uses the color picker mantine component for color selection. When running as a python package executable, all components appear as expected. 

I also have a version that creates a binary executable from the package using [pyapp as described here](https://ofek.dev/pyapp/latest/build/). The executable appears to work, but when I visit the app URL, the mantine color picker component is missing, with the following console error:

```
Error: @mantine/core: MantineProvider was not found in component tree, make sure you have it in your app
    at t.useMantineTheme (dash_mantine_components.v0_14_4m1723471859.js:2:1572687)
    at t.useProps (dash_mantine_components.v0_14_4m1723471859.js:2:1591483)
    at dash_mantine_components.v0_14_4m1723471859.js:2:1241288
    at we (react-dom@16.v2_17_1m1723471904.14.0.min.js:84:293)
    at nh (react-dom@16.v2_17_1m1723471904.14.0.min.js:96:43)
    at zj (react-dom@16.v2_17_1m1723471904.14.0.min.js:230:425)
    at Th (react-dom@16.v2_17_1m1723471904.14.0.min.js:152:223)
    at tj (react-dom@16.v2_17_1m1723471904.14.0.min.js:152:152)
    at Te (react-dom@16.v2_17_1m1723471904.14.0.min.js:146:151)
    at react-dom@16.v2_17_1m1723471904.14.0.min.js:61:68
```

**Comment by AnnMarieW** [comment]
Hi @matt-sd-watson 

What version of dmc are you using?  As of 0.14 the `MantineProvider` is required.  If you are not using the latest dmc version, it looks like you need to specify the version in the `pyapp` when you create the executable.

**Comment by matt-sd-watson** [comment]
@AnnMarieW thanks for the suggestion! It looks like pyapp will override any package version specified in the requirements in favor of those in the setup file. Downgrading the version across all files removes the issue.
